image: gcc

cache:
  paths:
    - build/spicygoat
    - build/spicygoat.exe
    - packaging/archlinux/spicygoat-*.pkg.tar.zst

build_linux:
  stage: build
  script:
    - apt-get update
    - apt-get -y install openjdk-17-jre-headless python3-pip xxd
    - wget -nv https://github.com/Kitware/CMake/releases/download/v3.25.2/cmake-3.25.2-linux-x86_64.sh
    - chmod +x cmake-3.25.2-linux-x86_64.sh
    - ./cmake-3.25.2-linux-x86_64.sh --skip-license --prefix=/
    - sh build.sh
  artifacts:
    paths:
      - build/spicygoat

.build_windows:
  stage: build
  tags: [windows-shell]
  script:
    - C:\msys64\msys2_shell.cmd -mingw64 -defterm -here -full-path -no-start build.sh
  artifacts:
    paths:
      - build/spicygoat.exe

package_archlinux:
  stage: build
  when: on_success
  image: archlinux:base-devel
  script:
    - cd packaging/archlinux
    - rm -f *.pkg.tar.zst
    - chmod o+w .
    - ln -s ../../build/spicygoat .
    - su -s /bin/sh -c 'makepkg -d -f' nobody

deploy:
  stage: deploy
  when: on_success
  script:
    - 'eval $(ssh-agent -s)'
    - echo "$SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add -
    - mkdir -p ~/.ssh
    - chmod 700 ~/.ssh
    - echo "$SSH_KNOWN_HOSTS" >> ~/.ssh/known_hosts
    - chmod 644 ~/.ssh/known_hosts
    - scp packaging/archlinux/spicygoat-$CI_PIPELINE_IID-1-x86_64.pkg.tar.zst root@arch.kinrar.io:/srv/repo/kinrar/x86_64
    - ssh root@arch.kinrar.io "cd /srv/repo/kinrar/x86_64; repo-add -n -R -p kinrar.db.tar.gz spicygoat-$CI_PIPELINE_IID-1-x86_64.pkg.tar.zst"
  only:
    - master
